### ISSUE TITLE
Recently Picked Emoji Functionality

### ISSUE THREAD

**Issue by syedsadiqali** [DCzajkowski/vue-emoji-picker#17]
Hi @DCzajkowski,
I have recently used this in some project, and i have extended the functionality to include a functionality to update recent emojis used by the into the recent group, it'll not update the file but it'll just take those emoji from either database or localStorage.

should i add a pull request for that?? will that be good ??

**Comment by DCzajkowski** [comment]
Can this be implemented easily without modifying the library? I think it should be, right? If so, I would not make a PR, but you can post your solution on CodePen/JSFiddle/CodeSandbox and link it here for others to use :)

**Comment by syedsadiqali** [comment]
sure, i'll link it here, may be next Sunday. thanks for reply. but can i ask why this can't be merged with the library itself, this will just increase the usability of the library ??

**Comment by DCzajkowski** [comment]
It's more like: if something can be done already, I don't see a point in baking it into core. I tried to make this library as lightweight and as customizable as possible. Since you are able to implement your feature without modifying the library, I think I have achieved my goal. 😉 

The problem with adding this feature is what if someone want to use IndexedDB or cookies instead of LocalStorage? What if someone is using it in a webview and doesn't have an access to localstorage? What if someone wants to hold the state in vuex instead? Current implementation of the library gives this flexibility. 

Unless there are some things we can improve, let me know 😉

**Comment by syedsadiqali** [comment]
I got your point, but even I'm not depending on Localstorage, and I have
extended the functionality of your src in my app, I'm not using it as a mom
package.

I can't use it as is, i have to change things and use it as a custom Code
in my app.

I hope you get the point.

**Comment by DCzajkowski** [comment]
I have implemented it for you without modifying the library [here](https://codepen.io/DCzajkowski/pen/gObWjEQ). I hope it helps.

**Comment by syedsadiqali** [comment]
Hi @DCzajkowski , I will have a look, thanks for your time.

**Comment by DCzajkowski** [comment]
I'll close this. If you have any questions please don't hesitate to ask 😉

**Comment by gurupras** [comment]
I'm looking at your pen, and I notice that there is a significant overhead to storing recent emoji due to the reverse-lookup. This probably feels like an issue hijack, but given the relevance, can we please get a second argument to `insert()` that includes the name (key of the `emojiTable`)?

**Comment by sherifmayika** [comment]
Hi
@DCzajkowski, @syedsadiqali, @Edza, @calebbergman,

I have implemented this with partial success.  I get everything loaded, except "RECENT" not added to the emoji list.
Your help is greatly appreciated. 

//my store/index.js 

`import recentEmojis from   "./modules/recentEmojis";

Vue.use(Vuex);

export default new Vuex.Store({
  modules: {
    recentEmojis,
  },`

// store//modules/recentEmojis/index.js

` /* A map of default emojis. It is included in the library and can be imported directly. */

export const defaultEmojis = {
  "Frequently used": {
    thumbs_up: "👍",
    red_hreat: "❤️",
    backhand_index_pointing_down: "👇",
    "-1": "👎",
     },
  People: {
    smile: "😄",   
  },
  Nature: {   
    rainbow: "🌈",
    ocean: "🌊",
  },
  Objects: {     
    smoking: "🚬",  
    tomato: "🍅",
    corn: "🌽",
  },
  Places: {     
    police_car: "🚓",    
    triangular_flag_on_post: "🚩",
  },
  Symbols: {
    keycap_ten: "🔟",
    heavy_plus_sign: "➕",
    small_blue_diamond: "🔹",
  },
};'
'
/* A helper function, since the name is not returned in the `append` function */
const getName = (emoji) => {
console.log("getName");
  const emojiMap = Object.values(defaultEmojis).reduce(
    (a, b) => ({ ...a, ...b }),
    {}
  );

    const object = Object.entries(emojiMap).find(
      // eslint-disable-next-line no-unused-vars
      ([_name, value]) => value === emoji
    );

  return object ? object[0] : null;
};

/* A Vuex module to include in Vuex. Its state can be persisted, etc. */
 // eslint-disable-next-line no-unused-vars



export default {
  namespaced: true,
  defaultEmojis,

  state: {
    recentlyUsedEmojis: [],
  },
  mutations: {
    recentlyUsedEmojis: (state, recentlyUsedEmojis) =>
      (state.recentlyUsedEmojis = recentlyUsedEmojis),
  },
  actions: {
    addEmojiToRecent: ({ state, commit }, emoji) => {
      
      const name = getName(emoji);

      const rest = state.recentlyUsedEmojis
        .map(
          // eslint-disable-next-line no-unused-vars
          ([_name, value]) => value
        )
        .includes(emoji)
        ? state.recentlyUsedEmojis.filter(
            // eslint-disable-next-line no-unused-vars
            ([_name, value]) => value !== emoji
          )
        : state.recentlyUsedEmojis.length > 5
        ? state.recentlyUsedEmojis.slice(0, -1)
        : state.recentlyUsedEmojis;

      commit("recentlyUsedEmojis", [[name, emoji], ...rest]);
    },
  },
  getters: {
    recentlyUsedEmojis: (state) =>
      state.recentlyUsedEmojis.length
        ? { Recent: Object.fromEntries(state.recentlyUsedEmojis) }
        : {},
  },
}
`
in my  vue instance  @  src/pages/edtor.default.vue
`...
<emoji-picker :emoji-table="emojis" @emoji="append" :search="search"
....
<script>
  import axios from "axios";
  import EmojiPicker from "vue-emoji-picker"
 import { defaultEmojis } from "../../store/modules/recentEmojis/index.js"
  export default {
    name: "ABCD",
    components: {
      EmojiPicker,
    },
...
    computed: {
    emojis() { 
    return { ...this.$store.getters.recentlyUsedEmojis, ...defaultEmojis }      
    }, 
    },
......
 methods: {
    append(emoji) {
        this.input += emoji
        this.$store.dispatch("recentEmojis/addEmojiToRecent", emoji)
      },
}`

**Comment by sherifmayika** [comment]
> Hi @DCzajkowski, @syedsadiqali, @Edza, @calebbergman,
> 
> I have implemented this with partial success. I get everything loaded, except "RECENT" not added to the emoji list. Your help is greatly appreciated.
> 
> //my store/index.js
> 
> `import recentEmojis from "./modules/recentEmojis";
> 
> Vue.use(Vuex);
> 
> export default new Vuex.Store({ modules: { recentEmojis, },`
> 
> // store//modules/recentEmojis/index.js
> 
> ` /* A map of default emojis. It is included in the library and can be imported directly. */
> 
> export const defaultEmojis = { "Frequently used": { thumbs_up: "+1", red_hreat: "heart", backhand_index_pointing_down: "point_down", "-1": "-1", }, People: { smile: "smile", }, Nature: { rainbow: "rainbow", ocean: "ocean", }, Objects: { smoking: "smoking", tomato: "tomato", corn: "corn", }, Places: { police_car: "police_car", triangular_flag_on_post: "triangular_flag_on_post", }, Symbols: { keycap_ten: "keycap_ten", heavy_plus_sign: "heavy_plus_sign", small_blue_diamond: "small_blue_diamond", }, };' ' /* A helper function, since the name is not returned in the `append` function */ const getName = (emoji) => { console.log("getName"); const emojiMap = Object.values(defaultEmojis).reduce( (a, b) => ({ ...a, ...b }), {} );
> 
> ```
> const object = Object.entries(emojiMap).find(
>   // eslint-disable-next-line no-unused-vars
>   ([_name, value]) => value === emoji
> );
> ```
> 
> return object ? object[0] : null; };
> 
> /* A Vuex module to include in Vuex. Its state can be persisted, etc. */ // eslint-disable-next-line no-unused-vars
> 
> export default { namespaced: true, defaultEmojis,
> 
> state: { recentlyUsedEmojis: [], }, mutations: { recentlyUsedEmojis: (state, recentlyUsedEmojis) => (state.recentlyUsedEmojis = recentlyUsedEmojis), }, actions: { addEmojiToRecent: ({ state, commit }, emoji) => {
> 
> ```
>   const name = getName(emoji);
> 
>   const rest = state.recentlyUsedEmojis
>     .map(
>       // eslint-disable-next-line no-unused-vars
>       ([_name, value]) => value
>     )
>     .includes(emoji)
>     ? state.recentlyUsedEmojis.filter(
>         // eslint-disable-next-line no-unused-vars
>         ([_name, value]) => value !== emoji
>       )
>     : state.recentlyUsedEmojis.length > 5
>     ? state.recentlyUsedEmojis.slice(0, -1)
>     : state.recentlyUsedEmojis;
> 
>   commit("recentlyUsedEmojis", [[name, emoji], ...rest]);
> },
> ```
> 
> }, getters: { recentlyUsedEmojis: (state) => state.recentlyUsedEmojis.length ? { Recent: Object.fromEntries(state.recentlyUsedEmojis) } : {}, }, } `in my vue instance @ src/pages/edtor.default.vue`... <emoji-picker :emoji-table="emojis" @emoji="append" :search="search" ....
> 
> <script> import axios from "axios"; import EmojiPicker from "vue-emoji-picker" import { defaultEmojis } from "../../store/modules/recentEmojis/index.js" export default { name: "ABCD", components: { EmojiPicker, }, ... computed: { emojis() { return { ...this.$store.getters.recentlyUsedEmojis, ...defaultEmojis } }, }, ...... methods: { append(emoji) { this.input += emoji this.$store.dispatch("recentEmojis/addEmojiToRecent", emoji) }, }`

solved
